### ISSUE TITLE
Global Margin Bugfix

### ISSUE THREAD

**Issue by rpire** [rpire/portfolio#12]
The margins of the page are currently set using the `padding` property directly in the document element. This must be changed to using the `margin` property on elements requiring these margins.

A recommendation for applying the required changes in creating a **mixin** with the necessary margin attributes and including it in elements that require margins, for example:

```scss
@mixin global-margins {
  margin-left: 5%;
  margin-right: 5%;
}

// ....

.element-with-margin {
  @include globa-margin;
}
```
